# Generated by Django 3.0.3 on 2020-08-01 18:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200801_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='entry_pic',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='media/'),
            preserve_default=False,
        ),
    ]
