# Generated by Django 3.0.3 on 2020-08-05 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200805_2225'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
